;#include"Device_Manager.inc"
;#include"Uart_Protocol.inc"
;#include"Buffer_Protocol.inc"
;#include"Delays_Manager.inc"
;#include"System_Set_Up.inc"
    
;===============================================================================
; CONSTANTES
;===============================================================================
SPBRG_VAL       EQU     .25         ; 9600 bps @ 4MHz
BUFFER_SIZE     EQU     .80         ; Tamaño buffer recepción





