#include"Digit_Manager.inc"
#include"Delays.inc" ; Solo se incluyo para hacer preubas con los delays y los digitos
    
    extern Delay_1ms
    extern Delay_1s
    extern Delay_100ms
    extern Delay_10ms
 

    extern Digit_0
    extern Digit_1
    extern Digit_2
    extern Digit_3
    extern Digit_4
    extern Digit_5
    extern Digit_6
    extern Digit_7
    extern Digit_8
    extern Digit_9
    
    extern Test_0
    extern Test_1
    
    extern SOSUD
    extern SOSTD
    extern SOMUD
    extern SOMTD
    
    
    
    